development:
  adapter: sqlite3
  database: db/ruboto_api_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/ruboto_api_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/ruboto_api_production.sqlite3
  pool: 5
  timeout: 5000
